from metadata import MetadataClient

c = MetadataClient("admin", "romdoul-v1cgt5jkq492dhzymlwr")
print("1. health:", c.health()["status"])
s = c.stats()
print("2. stats: total=%s edited=%s" % (s["total"], s["edited"]))
r = c.list_records(page_size=2, sort="created_at:desc")
print("3. records: total=%s newest=%s" % (r["total"], r["items"][0]["type"]))
rec = c.get_record(r["items"][0]["id"])
print("4. detail: type=%s status=%s model=%s" % (rec["type"], rec["status"], rec["source_model"]))
h = c.record_history(r["items"][0]["id"])
print("5. history: %s events" % len(h))
csv = c.export_csv(page_size=2)
print("6. csv: %s bytes" % len(csv))
jx = c.export_json(page_size=1)
print("7. json export: %s records" % len(jx))
print("ALL PASS ✓")
